### PR TITLE
Basic gaussian noise augmenter

### PR DESCRIPTION
**Pull request by alekepd**
Adds a non-jax based gaussian augmenter. Only supports diagonal convariances with a single value.

### CODE REVIEW

**Comment by alekepd** [comment]
Mostly neatened code and moved things around as discussed. I suggest to make this a numpy method, and then when you call it externally use as_array or from_numpy for the torch connections? Or we can make a torch aware class.

**Comment by alekepd** [comment]
Did not check correctness of methods.

**Comment by alekepd** [comment]
I changed your test for identity for now to just be based on _ident. Not sure how to handle this perfectly right now because you probably shouldn't use linear map knowledge? But you will have to, as else you cannot hard code derivatives.

**Comment by alekepd** [comment]
Okay, we will be fine. Just check to make sure your premap/postmap is a Linear Map object and we can make the typehints work: https://www.stefaanlippens.net/circular-imports-type-hints-python.html

**Comment by alekepd** [comment]
> Okay, we will be fine. Just check to make sure your premap/postmap is a Linear Map object and we can make the typehints work: https://www.stefaanlippens.net/circular-imports-type-hints-python.html

This actually wasn't sufficient, but we should still be okay.

**Comment by yaoyic** [comment]
I don't know what is with this black CI check. Locally my black says OK but it fails in the test here. Maybe a different version?
```
$ black --version
black, 24.3.0 (compiled: yes)
Python (CPython) 3.9.7
```

**Comment by alekepd** [comment]
Yes, just a black version thing. Fixed, and I also merged into changes from main.

**Pull request merged**
